---
name: webhook_del_vpn_ipsec
pack: "vyatta"
description: "Rule deleting VPN IPSec from a webhook payload"
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "vrouter"
criteria:
  trigger.body.task:
    type: "contains"
    pattern: "del_vpn_ipsec"
action:
  ref: vyatta.del_vpn_ipsec
  parameters:
    deviceIP: "{{trigger.body.deviceIP}}"
