---
name: webhook_cfg_fw_instance
pack: "vyatta"
description: "Rule configuring a FW instance from a webhook payload"
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "vrouter"
criteria:
  trigger.body.task:
    type: "contains"
    pattern: "cfg_fw_instance"
action:
  ref: vyatta.cfg_fw_instance
  parameters:
    deviceIP: "{{trigger.body.deviceIP}}"
    fw_instance_name: "{{trigger.body.fw_instance_name}}"
    intfNum: "{{trigger.body.intfNum}}"
    direction: "{{trigger.body.direction}}"