---
name: webhook_cfg_fw_rule
pack: "vyatta"
description: "Rule configuring a FW rule from a webhook payload"
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "vrouter"
criteria:
  trigger.body.task:
    type: "contains"
    pattern: "cfg_fw_rule"
action:
  ref: vyatta.cfg_fw_rule
  parameters:
    deviceIP: "{{trigger.body.deviceIP}}"
    fw_instance_name: "{{trigger.body.fw_instance_name}}"
    rule_number: "{{trigger.body.rule_number}}"
    rule_content: "{{trigger.body.rule_content}}"