---
name: webhook_cfg_ipsec
pack: "vyatta"
description: "Rule configuring an IPSec tunnel from a webhook payload"
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "vrouter"
criteria:
  trigger.body.task:
    type: "contains"
    pattern: "cfg_ipsec"
action:
  ref: vyatta.cfg_ipsec
  parameters:
    eastDeviceIP: "{{trigger.body.eastDeviceIP}}"
    eastTunnelIP: "{{trigger.body.eastTunnelIP}}"
    eastPrefix: "{{trigger.body.eastPrefix}}"
    westDeviceIP: "{{trigger.body.westDeviceIP}}"
    westTunnelIP: "{{trigger.body.westTunnelIP}}"
    westPrefix: "{{trigger.body.westPrefix}}"